# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField(default=1)),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Percent dicount to apply to the cheapest product', max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Percent dicount to apply to the cheapest product', max_digits=3)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='freeproduct',
            unique_together=set([('product', 'quantity_required')]),
        ),
    ]
