# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product', to_field='uid'),
        ),
        migrations.AlterUniqueTogether(
            name='freeproduct',
            unique_together=set([]),
        ),
    ]
